#ifndef EINSUM_SINGLE_INCLUDE_HPP
#define EINSUM_SINGLE_INCLUDE_HPP
// Amalgamated single-header — do not edit manually.
// Generated by scripts/amalgamate.py

#include <boost/hana.hpp>
#include <experimental/mdspan>
#include <type_traits>
#include <iostream>
#include <tuple>

// ---- einsum_helpers.hpp ----
//
// Shared compile-time helpers used by both einsum.hpp and unary_einsum.hpp.
//

#define DECAY(x) std::remove_cvref_t<x>
#define FWD_H(x) std::forward<decltype(x)>(x)

#if NDEBUG
#define PRINT_ITERATION(...)
#else
#define PRINT_ITERATION(lindices, rindices, out_indices)                       \
  print_sequence(out_indices);                                                 \
  std::cout << " += ";                                                         \
  print_sequence(lindices);                                                    \
  std::cout << " * ";                                                          \
  print_sequence(rindices);                                                    \
  std::cout << "\n";
#endif

namespace einsum_detail {

template <typename Keys, typename Values>
consteval auto make_map_from_sequences(Keys &&keys, Values &&values) {
  return boost::hana::unpack(
      boost::hana::zip(FWD_H(keys), FWD_H(values)), [](auto &&...tuples) {
        return boost::hana::make_map(boost::hana::make_pair(
            boost::hana::at_c<0>(tuples), boost::hana::at_c<1>(tuples))...);
      });
}

// Like make_map_from_sequences but silently drops duplicate keys (first wins).
// Required for unary einsum with repeated labels, e.g. "ii->" where left_labels
// contains 'i' twice — Hana maps require unique keys.
template <typename Keys, typename Values>
consteval auto make_unique_map_from_sequences(Keys keys, Values values) {
  return boost::hana::fold_left(
      boost::hana::zip(std::move(keys), std::move(values)),
      boost::hana::make_map(), [](auto acc, auto pair) {
        return boost::hana::if_(
            boost::hana::contains(acc, boost::hana::at_c<0>(pair)), acc,
            boost::hana::insert(
                acc, boost::hana::make_pair(boost::hana::at_c<0>(pair),
                                            boost::hana::at_c<1>(pair))));
      });
}

template <typename LMap, typename RMap>
consteval bool perform_input_check(LMap &&lmap, RMap &&rmap) {
  auto common_keys = boost::hana::intersection(FWD_H(lmap), FWD_H(rmap));
  auto ok = boost::hana::all_of(std::move(common_keys), [&](auto &&key) {
    return lmap[key] == rmap[key];
  });
  return ok;
}

template <typename Extents> consteval auto make_iota(Extents &&extents) {
  auto iotas =
      boost::hana::transform(std::forward<Extents>(extents), [](auto v) {
        return boost::hana::unpack(
            boost::hana::make_range(boost::hana::size_c<0>, v), [](auto... xs) {
              return boost::hana::tuple_c<std::size_t, xs...>;
            });
      });
  return iotas;
}

template <typename ValueList, typename Key>
consteval auto make_output_iterator_label_map(ValueList &&iterator_indices,
                                              Key &&label) {
  auto maps = boost::hana::transform(
      std::forward<ValueList>(iterator_indices), [&](auto &&tup) {
        auto pairs = boost::hana::zip_with(
            [](auto &&k, auto &&v) {
              return boost::hana::make_pair(FWD_H(k), FWD_H(v));
            },
            FWD_H(label), FWD_H(tup));
        return boost::hana::unpack(std::move(pairs), boost::hana::make_map);
      });
  return maps;
}

template <typename Dims> consteval auto get_extents(Dims &&dims) {
  return boost::hana::unpack(std::forward<Dims>(dims), [](auto... d) {
    return std::extents<std::size_t, d...>();
  });
}

} // namespace einsum_detail

// ---- labels.hpp ----
//
// Created by sayan on 9/18/25.
//


namespace einsum_detail {
template <typename LLabels, typename RLabels, typename OutLabels>
consteval auto make_collapsed_labels(LLabels ll, RLabels rl, OutLabels ol) {
  auto sorted_input_labels = boost::hana::sort(boost::hana::concat(ll, rl));
  auto diff = boost::hana::filter(sorted_input_labels, [&](auto l) {
    return boost::hana::not_(boost::hana::contains(ol, l));
  });
  return boost::hana::unique(diff);
}
} // namespace einsum_detail

template <typename LSeq, typename RSeq, typename OutSeq> struct Labels {
  static_assert(false);
};

template <char... Ls, char... Rs, char... Out>
struct Labels<boost::hana::string<Ls...>, boost::hana::string<Rs...>,
              boost::hana::string<Out...>> {
  constexpr static auto left_labels =
      boost::hana::make_tuple(boost::hana::char_c<Ls>...);
  constexpr static auto right_labels =
      boost::hana::make_tuple(boost::hana::char_c<Rs>...);
  constexpr static auto out_labels =
      boost::hana::make_tuple(boost::hana::char_c<Out>...);
  constexpr static auto collapsed_labels = einsum_detail::make_collapsed_labels(
      left_labels, right_labels, out_labels);
};

template <char... Ls, char... Rs, char... Out>
consteval auto make_labels(boost::hana::string<Ls...>,
                           boost::hana::string<Rs...>,
                           boost::hana::string<Out...>) {
  return Labels<boost::hana::string<Ls...>, boost::hana::string<Rs...>,
                boost::hana::string<Out...>>{};
}

template <typename> inline constexpr bool is_labels_v = false;
template <char... Ls, char... Rs, char... Out>
inline constexpr bool
    is_labels_v<Labels<boost::hana::string<Ls...>, boost::hana::string<Rs...>,
                       boost::hana::string<Out...>>> = true;

template <typename T>
concept CLabels = is_labels_v<std::remove_cvref_t<T>>;

template <typename LSeq, typename OutSeq> struct UniLabels {
  static_assert(false);
};

template <char... Ls, char... Out>
struct UniLabels<boost::hana::string<Ls...>, boost::hana::string<Out...>> {
  constexpr static auto left_labels =
      boost::hana::make_tuple(boost::hana::char_c<Ls>...);
  constexpr static auto out_labels =
      boost::hana::make_tuple(boost::hana::char_c<Out>...);
  constexpr static auto collapsed_labels = einsum_detail::make_collapsed_labels(
      left_labels, boost::hana::make_tuple(), out_labels);
};

template <char... Ls, char... Out>
consteval auto make_uni_labels(boost::hana::string<Ls...>,
                               boost::hana::string<Out...>) {
  return UniLabels<boost::hana::string<Ls...>, boost::hana::string<Out...>>{};
}

template <typename> inline constexpr bool is_uni_labels_v = false;
template <char... Ls, char... Out>
inline constexpr bool is_uni_labels_v<
    UniLabels<boost::hana::string<Ls...>, boost::hana::string<Out...>>> = true;

template <typename T>
concept CUniLabels = is_uni_labels_v<std::remove_cvref_t<T>>;

template <typename Out, typename... Inputs> struct NLabels {
  constexpr static auto out_labels =
      boost::hana::unpack(Out{}, boost::hana::make_tuple);
  constexpr static auto all_input_labels = boost::hana::make_tuple(
      boost::hana::unpack(Inputs{}, boost::hana::make_tuple)...);

  constexpr static auto all_labels_flat = boost::hana::fold_left(
      all_input_labels, boost::hana::make_tuple(),
      [](auto acc, auto labels) { return boost::hana::concat(acc, labels); });

  constexpr static auto collapsed_labels = boost::hana::unique(
      boost::hana::sort(boost::hana::filter(all_labels_flat, [](auto l) {
        return boost::hana::not_(boost::hana::contains(out_labels, l));
      })));
};

template <typename Out, typename... Inputs>
consteval auto make_n_labels(Out, Inputs...) {
  return NLabels<Out, Inputs...>{};
}

template <typename> inline constexpr bool is_n_labels_v = false;
template <typename Out, typename... Inputs>
inline constexpr bool is_n_labels_v<NLabels<Out, Inputs...>> = true;

template <typename T>
concept CNLabels = is_n_labels_v<std::remove_cvref_t<T>>;

// ---- matrices.hpp ----
//
// Created by sayan on 9/18/25.
//


#define FWD(x) std::forward<decltype(x)>(x)

template <typename T, typename LExt, typename RExt> struct Matrices;

template <typename T, std::size_t... Ls, std::size_t... Rs>
struct Matrices<T, std::index_sequence<Ls...>, std::index_sequence<Rs...>> {
  constexpr static auto left_extents =
      boost::hana::make_tuple(boost::hana::size_c<Ls>...);
  constexpr static auto right_extents =
      boost::hana::make_tuple(boost::hana::size_c<Rs>...);

  using value_type = T;
  using l_matrix_t = std::mdspan<T, std::extents<std::size_t, Ls...>>;
  using r_matrix_t = std::mdspan<T, std::extents<std::size_t, Rs...>>;

  l_matrix_t left;
  r_matrix_t right;
  constexpr Matrices(auto &&L_, auto &&R_) noexcept
      : left{FWD(L_)}, right{FWD(R_)} {}
};

template <typename T, std::size_t... Ls, std::size_t... Rs>
Matrices(std::mdspan<T, std::extents<std::size_t, Ls...>>,
         std::mdspan<T, std::extents<std::size_t, Rs...>>)
    -> Matrices<T, std::index_sequence<Ls...>, std::index_sequence<Rs...>>;

template <typename> inline constexpr bool is_matrices_v = false;
template <typename T, std::size_t... Ls, std::size_t... Rs>
inline constexpr bool is_matrices_v<
    Matrices<T, std::index_sequence<Ls...>, std::index_sequence<Rs...>>> = true;

template <typename M>
concept CMatrices = is_matrices_v<std::remove_cvref_t<M>>;

// ── Single operand
// ────────────────────────────────────────────────────────────

template <typename T, typename LExt> struct UniMatrices;

template <typename T, std::size_t... Ls>
struct UniMatrices<T, std::index_sequence<Ls...>> {
  constexpr static auto left_extents =
      boost::hana::make_tuple(boost::hana::size_c<Ls>...);

  using value_type = T;
  using l_matrix_t = std::mdspan<T, std::extents<std::size_t, Ls...>>;

  l_matrix_t left;
  constexpr explicit UniMatrices(auto &&L_) noexcept : left{FWD(L_)} {}
};

template <typename T, std::size_t... Ls>
UniMatrices(std::mdspan<T, std::extents<std::size_t, Ls...>>)
    -> UniMatrices<T, std::index_sequence<Ls...>>;

template <typename> inline constexpr bool is_uni_matrices_v = false;
template <typename T, std::size_t... Ls>
inline constexpr bool
    is_uni_matrices_v<UniMatrices<T, std::index_sequence<Ls...>>> = true;

template <typename M>
concept CUniMatrices = is_uni_matrices_v<std::remove_cvref_t<M>>;

namespace einsum_detail {

template <typename Seq> struct seq_to_extents;
template <std::size_t... Ls> struct seq_to_extents<std::index_sequence<Ls...>> {
  using type = std::extents<std::size_t, Ls...>;
};

template <std::size_t... Ls>
consteval auto seq_to_hana_extents(std::index_sequence<Ls...>) {
  return boost::hana::make_tuple(boost::hana::size_c<Ls>...);
}

template <typename Span> struct span_to_seq;
template <typename T, std::size_t... Ls>
struct span_to_seq<std::mdspan<T, std::extents<std::size_t, Ls...>>> {
  using type = std::index_sequence<Ls...>;
  using value_type = T;
};

} // namespace einsum_detail

// ── N-operand
// ─────────────────────────────────────────────────────────────────

template <typename T, typename... Seqs> struct NMatrices {
  using value_type = T;
  using spans_type = boost::hana::tuple<
      std::mdspan<T, typename einsum_detail::seq_to_extents<Seqs>::type>...>;

  constexpr static auto all_extents =
      boost::hana::make_tuple(einsum_detail::seq_to_hana_extents(Seqs{})...);

  spans_type spans;
  constexpr explicit NMatrices(
      std::mdspan<
          T, typename einsum_detail::seq_to_extents<Seqs>::type>... s) noexcept
      : spans{s...} {}
};

template <typename> inline constexpr bool is_n_matrices_v = false;
template <typename T, typename... Seqs>
inline constexpr bool is_n_matrices_v<NMatrices<T, Seqs...>> = true;

template <typename M>
concept CNMatrices = is_n_matrices_v<std::remove_cvref_t<M>>;

namespace einsum_detail {

template <typename... Spans> constexpr auto make_n_matrices(Spans... spans) {
  using T = typename span_to_seq<
      std::tuple_element_t<0, std::tuple<Spans...>>>::value_type;
  return NMatrices<T, typename span_to_seq<Spans>::type...>{spans...};
}

} // namespace einsum_detail

// ---- printers.hpp ----
//
// Created by sayan on 9/19/25.
//


template <typename Tuple> void print_tuple(const Tuple &tup) {
  std::cout << "(";
  bool first = true;
  boost::hana::for_each(tup, [&](auto const &x) {
    if (!first)
      std::cout << ", ";
    if constexpr (boost::hana::IntegralConstant<decltype(x)>::value) {
      std::cout << x.value;
    } else {
      std::cout << x;
    }
    first = false;
  });
  std::cout << ")";
}

template <typename Sequence> void print_sequence(const Sequence &seq) {
  std::cout << "[";
  bool first = true;
  boost::hana::for_each(seq, [&](auto const &x) {
    if (!first)
      std::cout << ", ";
    // if element is itself a tuple, delegate to tuple printer
    if constexpr (boost::hana::Sequence<decltype(x)>::value) {
      print_tuple(x);
    } else if constexpr (boost::hana::IntegralConstant<decltype(x)>::value) {
      std::cout << x.value;
    } else {
      std::cout << x;
    }
    first = false;
  });
  std::cout << "]";
}

template <typename Map> void print_map(const Map &map) {
  std::cout << "{";
  bool first = true;
  boost::hana::for_each(map, [&](auto const &pair) {
    if (!first)
      std::cout << ", ";
    first = false;

    auto key = boost::hana::first(pair);
    auto value = boost::hana::second(pair);
    std::cout << key << ": " << value;
  });
  std::cout << "}\n";
}

template <typename Map, typename Label>
void print_labeled_iterators(const Map &map, Label labels) {
  boost::hana::for_each(map, [&](auto const &m) {
    std::cout << "{ ";
    boost::hana::for_each(labels, [&](auto k) {
      std::cout << k.value << ": " << boost::hana::at_key(m, k) << " ";
    });
    std::cout << "}\n";
  });
}

// ---- einsum.hpp ----
//
// Created by sayan on 9/19/25.
//


using namespace einsum_detail;

template <CLabels Labels, CMatrices Matrices> struct Einsum {
private:
  using value_type = DECAY(Matrices)::value_type;
  constexpr static auto lmap = make_map_from_sequences(
      DECAY(Labels)::left_labels, DECAY(Matrices)::left_extents);
  constexpr static auto rmap = make_map_from_sequences(
      DECAY(Labels)::right_labels, DECAY(Matrices)::right_extents);
  static_assert(perform_input_check(lmap, rmap), "Input check failed");

public:
  constexpr static auto out_dims =
      boost::hana::transform(DECAY(Labels)::out_labels, [](auto key) {
        return boost::hana::at_key(boost::hana::union_(lmap, rmap), key);
      });
  constexpr static auto out_index_list =
      boost::hana::cartesian_product(make_iota(out_dims));

  constexpr static auto collapsed_dims =
      boost::hana::transform(DECAY(Labels)::collapsed_labels, [](auto key) {
        return boost::hana::at_key(boost::hana::union_(lmap, rmap), key);
      });
  constexpr static auto collapsed_index_list =
      boost::hana::cartesian_product(make_iota(collapsed_dims));

  constexpr static auto output_iterator_label_map =
      make_output_iterator_label_map(out_index_list, DECAY(Labels)::out_labels);

  constexpr static auto collapsed_iterator_label_map =
      make_output_iterator_label_map(collapsed_index_list,
                                     DECAY(Labels)::collapsed_labels);

  constexpr Einsum(std::same_as<Labels> auto &&,
                   std::same_as<Matrices> auto &&matrices) noexcept
      : result{}, left{FWD(matrices).left}, right{FWD(matrices).right} {}
  constexpr static auto extents = get_extents(out_dims);
  constexpr void eval() noexcept;
  [[nodiscard]] constexpr auto &get_result() const noexcept { return result; }
  [[nodiscard]] constexpr auto get_result_span() const noexcept {
    return std::mdspan<const value_type,
                       std::remove_const_t<decltype(extents)>>{result.data()};
  }

private:
  constexpr static auto output_size = boost::hana::fold_left(
      out_dims, std::size_t{1}, [](auto x, auto y) { return x * y.value; });
  std::array<value_type, output_size> result;
  DECAY(Matrices)::l_matrix_t left;
  DECAY(Matrices)::r_matrix_t right;
};

template <CLabels Labels, CMatrices Matrices>
Einsum(Labels &&, Matrices &&) -> Einsum<Labels, Matrices>;

template <CLabels Labels, CMatrices Matrices>
constexpr void Einsum<Labels, Matrices>::eval() noexcept {
  result.fill(value_type{});
  auto output =
      std::mdspan<value_type, DECAY(decltype(extents))>{result.data(), extents};

  auto assign_values = [&](auto &&lindices, auto &&rindices,
                           auto &&out_indices) {
    boost::hana::unpack(out_indices, [&](auto &&...out_idx) {
      boost::hana::unpack(lindices, [&](auto &&...l_idx) {
        boost::hana::unpack(rindices, [&](auto &&...r_idx) {
          output[out_idx.value...] +=
              left[l_idx.value...] * right[r_idx.value...];
        });
      });
    });
  };

  auto accumulate = [&](auto index_map) {
    auto get_index = [&](auto &&key) {
      return boost::hana::at_key(index_map, key);
    };
    auto lindices =
        boost::hana::transform(DECAY(Labels)::left_labels, get_index);
    auto rindices =
        boost::hana::transform(DECAY(Labels)::right_labels, get_index);
    auto out_indices =
        boost::hana::transform(DECAY(Labels)::out_labels, get_index);
    PRINT_ITERATION(lindices, rindices, out_indices);
    assign_values(lindices, rindices, out_indices);
  };

  if constexpr (boost::hana::size(DECAY(Labels)::collapsed_labels) == 0) {
    // no contraction: element-wise or outer product
    boost::hana::for_each(output_iterator_label_map,
                          [&](auto out_map) { accumulate(out_map); });
  } else if constexpr (boost::hana::size(DECAY(Labels)::out_labels) == 0) {
    // scalar output (e.g. "i,i->" dot product): iterate only collapsed indices
    boost::hana::for_each(
        collapsed_iterator_label_map,
        [&](auto collapsed_map) { accumulate(collapsed_map); });
  } else {
    // general contraction: outer = output indices, inner = collapsed indices
    boost::hana::for_each(output_iterator_label_map, [&](auto out_map) {
      boost::hana::for_each(
          collapsed_iterator_label_map, [&](auto collapsed_map) {
            accumulate(boost::hana::union_(out_map, collapsed_map));
          });
    });
  }
}

// ---- input_handler.hpp ----
//
// Created by sayan on 9/18/25.
//


namespace einsum_detail {

consteval auto tuple_to_string(auto &&tuple) {
  return boost::hana::unpack(tuple, [](auto &&...cs) {
    return boost::hana::string<std::decay_t<decltype(cs)>::value...>{};
  });
}

consteval auto stable_unique(auto &&xs) {
  return boost::hana::fold_left(
      xs, boost::hana::make_tuple(), [](auto acc, auto x) {
        return boost::hana::if_(boost::hana::contains(acc, x), acc,
                                boost::hana::append(acc, x));
      });
}

consteval auto parse_input(auto &&input_string) {
  auto [l, r, out] = boost::hana::unpack(input_string, [](auto &&...chars) {
    auto input = boost::hana::make_tuple(chars...);

    constexpr auto pos_comma = boost::hana::index_if(
        input, [](auto &&c) { return c == boost::hana::char_c<','>; });
    auto ls = boost::hana::take_front(input, *pos_comma);

    auto rest =
        boost::hana::drop_front(input, *pos_comma + boost::hana::size_c<1>);

    constexpr auto pos_arrow = boost::hana::index_if(
        rest, [](auto &&c) { return c == boost::hana::char_c<'-'>; });
    auto rs = boost::hana::take_front(rest, *pos_arrow);

    auto final =
        boost::hana::drop_front(rest, *pos_arrow + boost::hana::size_c<2>);

    return std::make_tuple(tuple_to_string(ls), tuple_to_string(rs),
                           tuple_to_string(final));
  });

  return boost::hana::make_tuple(std::move(l), std::move(r), std::move(out));
}

consteval auto make_label_from_inputs(auto input_string) {
  if constexpr (!boost::hana::contains(input_string,
                                       boost::hana::char_c<'-'>)) {
    auto input = boost::hana::unpack(
        input_string, [](auto... c) { return boost::hana::make_tuple(c...); });
    auto remove_comma = boost::hana::remove_if(input, [](auto c) {
      return boost::hana::bool_c<c == boost::hana::char_c<','>>;
    });

    auto result_str =
        boost::hana::concat(boost::hana::make_tuple(boost::hana::char_c<'-'>,
                                                    boost::hana::char_c<'>'>),
                            stable_unique(remove_comma));
    auto new_str = boost::hana::concat(input, result_str);
    return make_label_from_inputs(tuple_to_string(new_str));
  } else {
    auto lrout = parse_input(input_string);
    auto l = boost::hana::at_c<0>(lrout);
    auto r = boost::hana::at_c<1>(lrout);
    auto out = boost::hana::at_c<2>(lrout);
    return make_labels(std::move(l), std::move(r), std::move(out));
  }
}

consteval auto parse_unary_input(auto &&input_string) {
  auto [l, out] = boost::hana::unpack(input_string, [](auto &&...chars) {
    auto input = boost::hana::make_tuple(chars...);

    constexpr auto pos_arrow = boost::hana::index_if(
        input, [](auto &&c) { return c == boost::hana::char_c<'-'>; });
    auto ls = boost::hana::take_front(input, *pos_arrow);
    auto final =
        boost::hana::drop_front(input, *pos_arrow + boost::hana::size_c<2>);

    return std::make_tuple(tuple_to_string(ls), tuple_to_string(final));
  });
  return boost::hana::make_tuple(std::move(l), std::move(out));
}

consteval auto make_uni_label_from_inputs(auto input_string) {
  if constexpr (!boost::hana::contains(input_string,
                                       boost::hana::char_c<'-'>)) {
    auto input = boost::hana::unpack(
        input_string, [](auto... c) { return boost::hana::make_tuple(c...); });

    auto non_repeated = boost::hana::filter(stable_unique(input), [&](auto x) {
      auto count = boost::hana::fold_left(
          input, boost::hana::size_c<0>, [&](auto acc, auto c) {
            return boost::hana::if_(c == x, acc + boost::hana::size_c<1>, acc);
          });
      return count == boost::hana::size_c<1>;
    });

    auto arrow_tail =
        boost::hana::concat(boost::hana::make_tuple(boost::hana::char_c<'-'>,
                                                    boost::hana::char_c<'>'>),
                            non_repeated);
    auto new_str = boost::hana::concat(input, arrow_tail);
    return make_uni_label_from_inputs(tuple_to_string(new_str));
  } else {
    auto lout = parse_unary_input(input_string);
    auto l = boost::hana::at_c<0>(lout);
    auto out = boost::hana::at_c<1>(lout);
    return make_uni_labels(std::move(l), std::move(out));
  }
}

consteval auto parse_n_input(auto input_string) {
  auto chars = boost::hana::unpack(input_string, boost::hana::make_tuple);

  constexpr auto pos_arrow = boost::hana::index_if(
      chars, [](auto c) { return c == boost::hana::char_c<'-'>; });
  auto prefix = boost::hana::take_front(chars, *pos_arrow);
  auto output_chars =
      boost::hana::drop_front(chars, *pos_arrow + boost::hana::size_c<2>);

  auto fold_result = boost::hana::fold_left(
      prefix,
      boost::hana::make_pair(boost::hana::make_tuple(),
                             boost::hana::make_tuple()),
      [](auto acc, auto c) {
        auto segs = boost::hana::first(acc);
        auto cur = boost::hana::second(acc);
        return boost::hana::if_(
            c == boost::hana::char_c<','>,
            boost::hana::make_pair(
                boost::hana::append(segs, tuple_to_string(cur)),
                boost::hana::make_tuple()),
            boost::hana::make_pair(segs, boost::hana::append(cur, c)));
      });

  auto all_input_strings =
      boost::hana::append(boost::hana::first(fold_result),
                          tuple_to_string(boost::hana::second(fold_result)));
  auto output_string = tuple_to_string(output_chars);
  return boost::hana::make_pair(all_input_strings, output_string);
}

consteval auto make_n_label_from_inputs(auto input_string) {
  if constexpr (!boost::hana::contains(input_string,
                                       boost::hana::char_c<'-'>)) {
    auto chars = boost::hana::unpack(input_string, boost::hana::make_tuple);
    auto no_comma = boost::hana::remove_if(
        chars, [](auto c) { return c == boost::hana::char_c<','>; });
    auto non_repeated =
        boost::hana::filter(stable_unique(no_comma), [&](auto x) {
          auto count = boost::hana::fold_left(
              no_comma, boost::hana::size_c<0>, [&](auto acc, auto c) {
                return boost::hana::if_(c == x, acc + boost::hana::size_c<1>,
                                        acc);
              });
          return count == boost::hana::size_c<1>;
        });
    auto arrow_tail =
        boost::hana::concat(boost::hana::make_tuple(boost::hana::char_c<'-'>,
                                                    boost::hana::char_c<'>'>),
                            non_repeated);
    return make_n_label_from_inputs(
        tuple_to_string(boost::hana::concat(chars, arrow_tail)));
  } else {
    auto parsed = parse_n_input(input_string);
    auto input_strings = boost::hana::first(parsed);
    auto output_string = boost::hana::second(parsed);
    return boost::hana::unpack(input_strings, [&](auto... inp) {
      return make_n_labels(output_string, inp...);
    });
  }
}

} // namespace einsum_detail

// ---- n_einsum.hpp ----
//
// N-operand Einstein summation: "ij,jk,kl->il" with 3 or more tensors.
//

using namespace einsum_detail;

template <CNLabels Labels, CNMatrices Matrices> struct NEinsum {
private:
  using value_type = DECAY(Matrices)::value_type;

  // Build per-operand maps label→dim_size. Use make_unique_map_from_sequences
  // because a single operand may have repeated labels (e.g. "ii").
  constexpr static auto all_lmaps = boost::hana::transform(
      boost::hana::zip(DECAY(Labels)::all_input_labels,
                       DECAY(Matrices)::all_extents),
      [](auto pair) {
        return make_unique_map_from_sequences(boost::hana::at_c<0>(pair),
                                              boost::hana::at_c<1>(pair));
      });

  // Combined dimension map: union of all per-operand maps. For duplicate keys
  // hana::union_ keeps the first occurrence; dimensions were already validated
  // at map-construction time (static extents on the mdspans guarantee
  // consistency as long as the user wires the spans correctly — same guarantee
  // as binary Einsum).
  constexpr static auto combined_map = boost::hana::fold_left(
      all_lmaps, boost::hana::make_map(),
      [](auto acc, auto m) { return boost::hana::union_(acc, m); });

public:
  constexpr static auto out_dims =
      boost::hana::transform(DECAY(Labels)::out_labels, [](auto key) {
        return boost::hana::at_key(combined_map, key);
      });
  constexpr static auto out_index_list =
      boost::hana::cartesian_product(make_iota(out_dims));

  constexpr static auto collapsed_dims =
      boost::hana::transform(DECAY(Labels)::collapsed_labels, [](auto key) {
        return boost::hana::at_key(combined_map, key);
      });
  constexpr static auto collapsed_index_list =
      boost::hana::cartesian_product(make_iota(collapsed_dims));

  constexpr static auto output_iterator_label_map =
      make_output_iterator_label_map(out_index_list, DECAY(Labels)::out_labels);
  constexpr static auto collapsed_iterator_label_map =
      make_output_iterator_label_map(collapsed_index_list,
                                     DECAY(Labels)::collapsed_labels);

  constexpr NEinsum(std::same_as<Labels> auto &&,
                    std::same_as<Matrices> auto &&matrices) noexcept
      : result{}, matrices_{FWD(matrices)} {}

  constexpr static auto extents = get_extents(out_dims);
  constexpr void eval() noexcept;
  [[nodiscard]] constexpr auto &get_result() const noexcept { return result; }
  [[nodiscard]] constexpr auto get_result_span() const noexcept {
    return std::mdspan<const value_type,
                       std::remove_const_t<decltype(extents)>>{result.data()};
  }

private:
  constexpr static auto output_size = boost::hana::fold_left(
      out_dims, std::size_t{1}, [](auto x, auto y) { return x * y.value; });
  std::array<value_type, output_size> result;
  DECAY(Matrices) matrices_;
};

template <CNLabels Labels, CNMatrices Matrices>
NEinsum(Labels &&, Matrices &&) -> NEinsum<Labels, Matrices>;

template <CNLabels Labels, CNMatrices Matrices>
constexpr void NEinsum<Labels, Matrices>::eval() noexcept {
  result.fill(value_type{});
  auto output =
      std::mdspan<value_type, DECAY(decltype(extents))>{result.data(), extents};

  auto accumulate = [&](auto index_map) {
    auto get_index = [&](auto key) {
      return boost::hana::at_key(index_map, key);
    };
    auto out_indices =
        boost::hana::transform(DECAY(Labels)::out_labels, get_index);

    // Fold product: output[out...] += A[a...] * B[b...] * C[c...] * ...
    auto product = boost::hana::fold_left(
        boost::hana::zip(DECAY(Labels)::all_input_labels, matrices_.spans),
        value_type{1}, [&](auto acc, auto pair) {
          auto labels = boost::hana::at_c<0>(pair);
          auto span = boost::hana::at_c<1>(pair); // copy: spans are cheap
          auto indices = boost::hana::transform(labels, get_index);
          return acc * boost::hana::unpack(indices, [&](auto... idx) {
                   return span[idx.value...];
                 });
        });

    boost::hana::unpack(out_indices, [&](auto &&...out_idx) {
      output[out_idx.value...] += product;
    });
  };

  if constexpr (boost::hana::size(DECAY(Labels)::collapsed_labels) == 0) {
    // No contraction: element-wise / outer product across N operands.
    boost::hana::for_each(output_iterator_label_map,
                          [&](auto out_map) { accumulate(out_map); });
  } else if constexpr (boost::hana::size(DECAY(Labels)::out_labels) == 0) {
    // Scalar output: full contraction.
    boost::hana::for_each(collapsed_iterator_label_map,
                          [&](auto col_map) { accumulate(col_map); });
  } else {
    // General case: outer loop over output indices, inner over collapsed.
    boost::hana::for_each(output_iterator_label_map, [&](auto out_map) {
      boost::hana::for_each(collapsed_iterator_label_map, [&](auto col_map) {
        accumulate(boost::hana::union_(out_map, col_map));
      });
    });
  }
}

#define make_einsum(name, inputstring, ...)                                    \
  auto name = std::apply(                                                      \
      [](auto... _spans) {                                                     \
        auto m = einsum_detail::make_n_matrices(_spans...);                    \
        auto input = BOOST_HANA_STRING(inputstring);                           \
        auto labels = einsum_detail::make_n_label_from_inputs(input);          \
        return NEinsum{labels, m};                                             \
      },                                                                       \
      std::make_tuple(__VA_ARGS__));

#define make_einsum_n make_einsum

// ---- unary_einsum.hpp ----
//
// Single-operand Einstein summation: transpose, trace, diagonal, axis
// permutation.
//

using namespace einsum_detail;

template <CUniLabels ULabels, CUniMatrices UMatrices> struct UnaryEinsum {
private:
  using value_type = DECAY(UMatrices)::value_type;
  // Use unique-key variant: repeated labels (e.g. "ii") would otherwise create
  // duplicate keys in a Hana map, which is undefined behaviour.
  constexpr static auto lmap = make_unique_map_from_sequences(
      DECAY(ULabels)::left_labels, DECAY(UMatrices)::left_extents);

public:
  constexpr static auto out_dims =
      boost::hana::transform(DECAY(ULabels)::out_labels, [](auto key) {
        return boost::hana::at_key(lmap, key);
      });
  constexpr static auto out_index_list =
      boost::hana::cartesian_product(make_iota(out_dims));

  constexpr static auto collapsed_dims =
      boost::hana::transform(DECAY(ULabels)::collapsed_labels, [](auto key) {
        return boost::hana::at_key(lmap, key);
      });
  constexpr static auto collapsed_index_list =
      boost::hana::cartesian_product(make_iota(collapsed_dims));

  constexpr static auto output_iterator_label_map =
      make_output_iterator_label_map(out_index_list,
                                     DECAY(ULabels)::out_labels);
  constexpr static auto collapsed_iterator_label_map =
      make_output_iterator_label_map(collapsed_index_list,
                                     DECAY(ULabels)::collapsed_labels);

  constexpr UnaryEinsum(std::same_as<ULabels> auto &&,
                        std::same_as<UMatrices> auto &&matrices) noexcept
      : result{}, left{FWD(matrices).left} {}

  constexpr static auto extents = get_extents(out_dims);
  constexpr void eval() noexcept;
  [[nodiscard]] constexpr auto &get_result() const noexcept { return result; }
  [[nodiscard]] constexpr auto get_result_span() const noexcept {
    return std::mdspan<const value_type,
                       std::remove_const_t<decltype(extents)>>{result.data()};
  }

private:
  constexpr static auto output_size = boost::hana::fold_left(
      out_dims, std::size_t{1}, [](auto x, auto y) { return x * y.value; });
  std::array<value_type, output_size> result;
  DECAY(UMatrices)::l_matrix_t left;
};

template <CUniLabels ULabels, CUniMatrices UMatrices>
UnaryEinsum(ULabels &&, UMatrices &&) -> UnaryEinsum<ULabels, UMatrices>;

template <CUniLabels ULabels, CUniMatrices UMatrices>
constexpr void UnaryEinsum<ULabels, UMatrices>::eval() noexcept {
  result.fill(value_type{});
  auto output =
      std::mdspan<value_type, DECAY(decltype(extents))>{result.data(), extents};

  // Accumulate one index assignment: output[out...] += input[l...]
  // Repeated labels in left_labels (e.g. "ii") correctly map both positions
  // to the same index value, giving diagonal access.
  auto accumulate = [&](auto index_map) {
    auto get_index = [&](auto &&key) {
      return boost::hana::at_key(index_map, key);
    };
    auto lindices =
        boost::hana::transform(DECAY(ULabels)::left_labels, get_index);
    auto out_indices =
        boost::hana::transform(DECAY(ULabels)::out_labels, get_index);
    boost::hana::unpack(out_indices, [&](auto &&...out_idx) {
      boost::hana::unpack(lindices, [&](auto &&...l_idx) {
        output[out_idx.value...] += left[l_idx.value...];
      });
    });
  };

  if constexpr (boost::hana::size(DECAY(ULabels)::collapsed_labels) == 0) {
    // No contraction: permutation, identity, or diagonal extraction.
    boost::hana::for_each(output_iterator_label_map,
                          [&](auto out_map) { accumulate(out_map); });
  } else if constexpr (boost::hana::size(DECAY(ULabels)::out_labels) == 0) {
    // Scalar output: trace "ii->" or full contraction.
    boost::hana::for_each(
        collapsed_iterator_label_map,
        [&](auto collapsed_map) { accumulate(collapsed_map); });
  } else {
    // General unary contraction: e.g. partial trace over some indices.
    boost::hana::for_each(output_iterator_label_map, [&](auto out_map) {
      boost::hana::for_each(
          collapsed_iterator_label_map, [&](auto collapsed_map) {
            accumulate(boost::hana::union_(out_map, collapsed_map));
          });
    });
  }
}

#define make_einsum_unary(name, inputstring, spanA)                            \
  auto name = [_span = spanA]() {                                              \
    UniMatrices m{_span};                                                      \
    auto input = BOOST_HANA_STRING(inputstring);                               \
    auto labels = einsum_detail::make_uni_label_from_inputs(input);            \
    return UnaryEinsum{labels, m};                                             \
  }();

#endif // EINSUM_SINGLE_INCLUDE_HPP
